workflows:
  ios-production:
    name: iOS Production
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: Marshal.dev, Luminous
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.luminous.faceyoga
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        BUNDLE_ID: "com.luminous.faceyoga"
        CERTIFICATE_PASSWORD: marshal
        APP_STORE_CONNECT_KEY_ID: "598NXGQP94"
        APP_STORE_CONNECT_ISSUER_ID: "803c9557-3ebe-4980-8094-eefc59700039"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Set up code signing
        script: | 
          keychain initialize
          app-store-connect fetch-signing-files \
            "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create \
            --platform IOS \
            --certificate-key-password marshal \
            --key-id "$APP_STORE_CONNECT_KEY_ID" \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"

      - name: Configure Push Notifications
        script: |
          xcode-project enable-capability \
            --path ios/Runner.xcodeproj \
            --capability push-notifications

      - name: Update entitlements
        script: |
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>aps-environment</key>
              <string>production</string>
          </dict>
          </plist>' > ios/Runner/Runner.entitlements

      - name: Flutter build
        script: |
          flutter pub get
          flutter build ipa --release \
            --build-number=$(($(app-store-connect get-latest-testflight-build-number "$BUNDLE_ID") + 1)) \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log

    publishing:
      email:
        recipients:
          - marshcodes@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers