name: luminous_face_yoga
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+17

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_inappwebview: ^6.1.5
  awesome_notifications: ^0.7.4+1
  shared_preferences: ^2.3.3
  confetti: ^0.8.0
  lottie: ^3.1.0  
  timezone: ^0.10.0
  logger: ^1.4.0
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/loader_logo.png
    - assets/overlay_loader_icon.png
    - assets/animations/achievement_unlock.json
    - assets/images/celebration.png
